/** Suggestions for the bank name box. Users can still type any bank. */
export const NIGERIAN_BANKS = [
  "Access Bank",
  "Ecobank",
  "Fidelity Bank",
  "First Bank",
  "FCMB",
  "GTBank",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda",
  "Moniepoint",
  "OPay",
  "PalmPay",
  "Polaris Bank",
  "Providus Bank",
  "Stanbic IBTC",
  "Sterling Bank",
  "UBA",
  "Union Bank",
  "Unity Bank",
  "Wema Bank (ALAT)",
  "Zenith Bank",
] as const;
